[package]
name = "hashring-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
blake3 = "1"
prost = "0.13"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tonic = { version = "0.12", features = ["transport"] }
uuid = { version = "1", features = ["v4"] }
xxhash-rust = { version = "0.8", features = ["xxh3"] }

[build-dependencies]
protoc-bin-vendored = "3"
tonic-build = "0.12"
