[package]
name = "hashring-rs"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "crates/hashring-client",
    "crates/hashring-coordinator",
    "crates/hashring-core",
    "crates/hashring-experiment",
    "crates/hashring-node",
]
default-members = [
    ".",
    "crates/hashring-client",
    "crates/hashring-coordinator",
    "crates/hashring-core",
    "crates/hashring-experiment",
    "crates/hashring-node",
]
resolver = "2"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
hashring-client = { version = "0.1.0", path = "crates/hashring-client" }
hashring-coordinator = { version = "0.1.0", path = "crates/hashring-coordinator" }
hashring-core = { version = "0.1.0", path = "crates/hashring-core" }
hashring-experiment = { version = "0.1.0", path = "crates/hashring-experiment" }
hashring-node = { version = "0.1.0", path = "crates/hashring-node" }
hex = "0.4"
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
tonic = { version = "0.12", features = ["transport"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
tempfile = "3"

[profile.release]
debug = true
# 可选：同时保留符号名称
strip = false