[package]
name = "hashring-node"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
blake3 = "1"
hashring-core = { version = "0.1.0", path = "../hashring-core" }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync", "time"] }
tonic = { version = "0.12", features = ["transport"] }
tracing = "0.1"
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
tokio-stream = { version = "0.1", features = ["net"] }
